name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Build project
        run: npm run build
        env:
          REACT_APP_VERSION: ${{ github.sha }}

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: 'asiqut'
          user_email: 'sofyazemlanaya@gmail.com'
          commit_message: 'Deploy v${{ github.run_number }} [skip ci]'
          full_commit_message: 'Deploy v${{ github.run_number }} (${{ github.sha }}) [skip ci]'
          enable_jekyll: false
          keep_files: false
          force_orphan: true
